NA_VALUE = "           NA"

EXCLUDE_COUNTRIES = [
        "Africa CAMEU region, nes",
        "American Samoa",
        "Andorra",
        "Anguilla",
        "Antartica",
        "Antigua and Barbuda",
        "Areas, nes",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Br. Antarctic Terr.",
        "Br. Indian Ocean Terr.",
        "Bunkers",
        "Cabo Verde",
        "CACM, nes",
        "Caribbean, nes",
        "Comoros",
        "Curaçao",
        "Djibouti",
        "Equatorial Guinea",
        "EU-28",
        "Europe EFTA, nes",
        "Europe EU, nes",
        "Fiji",
        "Fmr Panama, excl.Canal Zone",
        "Fmr Rhodesia Nyas",
        "Fmr Tanganyika",
        "Fmr Zanzibar and Pemba Isd",
        "Fr. South Antarctic Terr.",
        "Free Zones",
        "French Guiana",
        "French Polynesia",
        "FS Micronesia",
        "Guadeloupe",
        "Guam",
        "Haiti",
        "Holy See",
        "Honduras",
        "India, excl. Sikkim",
        "Kiribati",
        "LAIA, nes",
        "Lao People's Dem. Rep.",
        "Madagascar",
        "Maldives",
        "Malta",
        "Martinique",
        "Mauritius",
        "Mayotte",
        "Montserrat",
        "Nauru",
        "Neth. Antilles",
        "Neth. Antilles and Aruba",
        "Neutral Zone",
        "New Caledonia",
        "Niue",
        "North America and Central America, nes",
        "Northern Africa, nes",
        "Oceania, nes",
        "Other Africa, nes",
        "Other Asia, nes",
        "Other Europe, nes",
        "Palau",
        "Papua New Guinea",
        "Pitcairn",
        "Rest of America, nes",
        "Réunion",
        "Ryukyu Isd",
        "Sabah",
        "Saint Barthélemy",
        "Saint Helena",
        "Saint Kitts and Nevis",
        "Saint Kitts, Nevis and Anguilla",
        "Saint Lucia",
        "Saint Maarten",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Seychelles",
        "Serbia and Montenegro",
        "So. African Customs Union",
        "Special Categories",
        "State of Palestine",
        "TFYR of Macedonia",
        "Timor-Leste",
        "Tokelau",
        "Tonga",
        "Trinidad and Tobago",
        "Tuvalu",
        "Vanuatu",
        "Western Asia, nes",
        "World",
        "Antarctica",
        "Macao SAR",
        "Eastern Europe",
        "nes Fmr Dem. Rep. of Vietnam",
        "Fmr Panama - Canal - Zone",
        "Bonaire",
        "Sikkim",
        "World",
    ]